config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'search' => 'welcome#search', as: :search

    resources :resorts

end

app/models/resort.rb
class Resort < ActiveRecord::Base

	include PgSearch
  pg_search_scope :search_by_nearest_airport, :against => :nearest_airport

	extend FriendlyId
	friendly_id :resort_name, use: :slugged

  def proportion_of(runs)
    runs.to_f / self.size_of_ski_domain.to_f * 100
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
	def show
		@resort = Resort.friendly.find(params[:id])
	end

	# def index
 #    	@resorts = Resort.all
 #    	@resort_search = Resort.search_by_nearest_airport(params[:search])
 #  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
		def index
    	@resorts = Resort.all
 			@resort_search = Resort.search_by_nearest_airport(params[:search])
  	end 

  def search
    @resorts = Resort.search_by_nearest_airport(params[:search])
    @data = Resort.all
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkiFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
  <%= csrf_meta_tags %>
  <meta charset='UTF-8'>        
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:500,400|Raleway+Dots' rel='stylesheet' type='text/css'>
  <link href="https://fontastic.s3.amazonaws.com/xvMrffBYnidDfDBtfu2Wd3/icons.css" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resorts/show.html.erb
<h1><%= @resort.resort_name %></h1>

app/views/welcome/index.html.erb
<header>
  <img id="logo" src="logo.png" alt="Mountain Finder Logo" style="width:20%;height:20%;">
  <section class="fancy-line"> </section>
</header>
<section class="navigation-bar">
  <nav>
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">Browse Resorts </a></li>
      <li><a href="#">Ski Holiday Tips</a></li>
      <li><a href="#">Blog </a></li>
    </ul>
  </nav>
</section>

<section class="fancy-line"> </section>
<section class="table-section">
  <h3>Browse Resorts</h3>
  <h4>Sort by column headers </h4>
  <table id="resortTable" class="tablesorter" cellspacing="1"> 
    <thead> 
      <tr> 
          <th>Resort</th>
          <th>Country</th> 
          <th>Nearest Airport</th> 
          <th>Transfer Time</th> 
          <th>Size of Ski Domain</th> 
          <th>Beginner Friendly</th> 
          <th>Apres Ski</th>
          <th>Off Piste</th> 
          <th>Cost of Day Pass</th>
          <th>Altitude</th> 
      </tr> 
    </thead> 
    <tbody> 
      <% @resorts.each do |resort| %>
        <tr> 
          <td><%= link_to resort.resort_name, resort_path(resort) %></td> 
          <td><%= resort.country %></td> 
          <td><%= resort.nearest_airport %></td> 
          <td><%= resort.transfer_time %></td> 
          <td><%= resort.size_of_ski_domain %> km<br>
            <a href="#" data-tool="<%= resort.resort_name %> pistes: <%= resort.easy_runs_km %>km Easy / <%= resort.medium_runs_km %>km Medium / <%= resort.hard_runs_km %>km Hard" class="tooltip">
              <section class='slope-difficulty-gauge'>
                <section class="easy-runs" id="<%= resort.proportion_of(resort.easy_runs_km).to_i %>-percent-easy-runs" style="width: <%= number_to_percentage(resort.proportion_of(resort.easy_runs_km), precision: 0) %>"></section>
                <section class="medium-runs" id="<%= resort.proportion_of(resort.medium_runs_km).to_i %>-percent-medium-runs" style="width: <%= number_to_percentage(resort.proportion_of(resort.medium_runs_km), precision: 0) %>"></section>
              </section>
            </a>
          </td>
          <td><%= resort.beginner_rating %>/5</td>
          <td>
            <div id="for-sort-hidden"><%= resort.apres_ski_rating %></div>
            <% if resort.apres_ski_rating == 5 %>
              <i id="good-rating" class="icon-beer"> </i>
              <i id="good-rating" class="icon-beer"> </i>
              <i id="good-rating" class="icon-beer"> </i>
            <% elsif resort.apres_ski_rating == 4 %>
              <i id="mid-rating" class="icon-beer"> </i>
              <i id="mid-rating" class="icon-beer"> </i>
            <% else %>
              <i id="bad-rating"class="icon-beer"> </i>
            <% end %>
          </td>
          <td><%= resort.off_piste_rating %></td>
          <td><%= resort.cost_of_pass%>€</td>
          <td><%= resort.altitude %>km</td>
        </tr> 
      <% end %>
    </tbody> 
  </table> 
</section>

<script type="text/javascript">
  $(document).ready(function() { 
    $("#resortTable").tablesorter({
      cssAsc: "headerSortUp", 
      cssDesc: "headerSortDown", 
      sortReset: true,
      sortInitialOrder: "asc",
      headers: {
        5: { sortInitialOrder: 'desc' },
        6: { sortInitialOrder: 'desc' },
        9: { sortInitialOrder: 'desc' }
      }
    }); 
  }); 
</script>